{"name": "test_authorization[data1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None\n +  where None = <bound method BaseSetup.check_if_element_exists of <Base.base.BaseSetup object at 0x042522B0>>(('css selector', 'nav ul.list-unstyled .sidebar-header:nth-child(2)'))\n +    where <bound method BaseSetup.check_if_element_exists of <Base.base.BaseSetup object at 0x042522B0>> = <Base.base.BaseSetup object at 0x042522B0>.check_if_element_exists\n +      where <Base.base.BaseSetup object at 0x042522B0> = <utilities.testFrame.InitPagesDriver object at 0x04252C50>.base\n +    and   ('css selector', 'nav ul.list-unstyled .sidebar-header:nth-child(2)') = locator.PROFILE", "trace": "app = <utilities.testFrame.InitPagesDriver object at 0x04252C50>, data = ['admin@gmail.com', '1qazqaz'], screenshot_on_failure = None\n\n    @allure.link(\"http://localhost:49862/home/events?page=1\", name='Click me')\n    @allure.feature('Login User')\n    @allure.story('\"Actors\" login to site EventExpress ')\n    @allure.severity(allure.severity_level.CRITICAL)\n    @pytest.mark.parametrize('data',credentials())\n    def test_authorization(app, data, screenshot_on_failure):\n        app.auth.click_on_login_button()\n        app.auth.clean_login_field()\n        app.auth.type_login(data[0])\n        app.auth.clean_password_field( )\n        app.auth.type_pass(data[1])\n        app.auth.press_button_signin()\n>       assert app.base.check_if_element_exists(locator.PROFILE)\nE       AssertionError: assert None\nE        +  where None = <bound method BaseSetup.check_if_element_exists of <Base.base.BaseSetup object at 0x042522B0>>(('css selector', 'nav ul.list-unstyled .sidebar-header:nth-child(2)'))\nE        +    where <bound method BaseSetup.check_if_element_exists of <Base.base.BaseSetup object at 0x042522B0>> = <Base.base.BaseSetup object at 0x042522B0>.check_if_element_exists\nE        +      where <Base.base.BaseSetup object at 0x042522B0> = <utilities.testFrame.InitPagesDriver object at 0x04252C50>.base\nE        +    and   ('css selector', 'nav ul.list-unstyled .sidebar-header:nth-child(2)') = locator.PROFILE\n\ntest_auth.py:24: AssertionError"}, "attachments": [{"name": "stdout", "source": "23c67583-f177-4bce-a7a6-220aa824b3c2-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "['admin@gmail.com', '1qazqaz']"}], "start": 1577194748697, "stop": 1577194762472, "uuid": "14050a17-c553-4e7b-9b76-730677c5f6c3", "historyId": "307b3e81a3c9742e74203e6924c08bb2", "testCaseId": "2a55ae64119e6f3ed897e368050f6f6b", "fullName": "Tests.test_auth#test_authorization", "labels": [{"name": "story", "value": "\"Actors\" login to site EventExpress "}, {"name": "feature", "value": "Login User"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "DESKTOP-R2070AB"}, {"name": "thread", "value": "17372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_auth"}], "links": [{"type": "link", "url": "http://localhost:49862/home/events?page=1", "name": "Click me"}]}